# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-23 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='permalink',
            field=models.CharField(default='hey', max_length=100),
            preserve_default=False,
        ),
    ]
