# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 12:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_post_permalink'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 24, 12, 8, 24, 173333, tzinfo=utc), verbose_name='date published'),
        ),
    ]
