# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 12:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20160724_1208'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'permissions': (('view_drafts', "View anyone's drafts"),)},
        ),
    ]
