# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-07-24 16:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_auto_20160724_1618'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='category',
            name='link',
            field=models.CharField(default='test', max_length=100),
            preserve_default=False,
        ),
    ]
