# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-11 15:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0013_auto_20160818_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published')),
                ('edit_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date editted')),
                ('body', models.TextField()),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Post')),
                ('reply_to', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Comment')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'permissions': (('edit_comments', "Edit anyone's comments"),),
            },
        ),
        migrations.RemoveField(
            model_name='userextra',
            name='user',
        ),
        migrations.DeleteModel(
            name='UserExtra',
        ),
    ]
