# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20161009_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='menulink',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
