# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0020_menulink_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.URLField(max_length=1024),
        ),
    ]
