# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-10-09 18:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20161009_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menulink',
            name='url',
            field=models.CharField(max_length=1024),
        ),
    ]
