# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cache',
            field=models.TextField(blank=True, null=True),
        ),
    ]
