# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-05 13:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_post_cache'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cache_hash',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
